# Generated by Django 2.2.2 on 2019-06-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first', models.CharField(max_length=25)),
                ('last', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('message', models.CharField(max_length=15000)),
            ],
            options={
                'ordering': ('created',),
                'managed': True,
            },
        ),
    ]
